const tbody = document.querySelector(".codes-table tbody");
const modal = document.getElementById("code-modal");
const modalTitle = document.getElementById("modal-title");

const scoreInput = document.getElementById("score-code");
const statInput = document.getElementById("stat-code");

let editingTeamId = null;

// Format expiration display
function formatExpirationInfo(expiresAt) {
  if (!expiresAt) return "Not yet set (set when game is marked final)";
  const date = new Date(expiresAt);
  const now = new Date();
  if (date < now) return `Expired: ${date.toLocaleString()}`;
  return `Expires: ${date.toLocaleString()}`;
}

// Load teams + codes
async function loadCodes() {
    const res = await authFetch("/teams");
    
    // Handle 401/403 errors (authFetch will redirect/show message)
    if (!res.ok) {
      console.error("Failed to load teams:", res.status);
      return;
    }
    
    const teams = await res.json();

    tbody.innerHTML = "";

    teams.forEach(t => {
        const tr = document.createElement("tr");

        const gmExpiration = formatExpirationInfo(t.gameManagerCodeExpiresAt);
        const smExpiration = formatExpirationInfo(t.statManagerCodeExpiresAt);

        tr.innerHTML = `
            <td>${t.name}</td>
            <td>${t.organizationName}</td>
            <td style="text-align:center;">
                <div>
                    <code style="color:#FFB300; font-weight: bold;">GM-${t.gameManagerCode || "—"}</code>
                    <br>
                    <small style="color:#999;">${gmExpiration}</small>
                </div>
            </td>
            <td style="text-align:center;">
                <div>
                    <code style="color:#42a5f5; font-weight: bold;">SM-${t.statManagerCode || "—"}</code>
                    <br>
                    <small style="color:#999;">${smExpiration}</small>
                </div>
            </td>
            <td style="text-align:center;">
                <button class="btn-sm edit-btn" data-id="${t.id}">ℹ️ Details</button>
            </td>
        `;

        tbody.appendChild(tr);
    });

    document.querySelectorAll(".edit-btn").forEach(btn =>
        btn.addEventListener("click", () => openEditModal(btn.dataset.id))
    );
}

async function openEditModal(id) {
    editingTeamId = id;

    const res = await authFetch(`/teams/${id}`);
    
    if (!res.ok) {
      console.error("Failed to load team:", res.status);
      return;
    }
    
    const t = await res.json();

    modalTitle.textContent = `Access Codes — ${t.name}`;

    scoreInput.value = t.gameManagerCode || "(not yet generated)";
    scoreInput.disabled = true;
    statInput.value = t.statManagerCode || "(not yet generated)";
    statInput.disabled = true;

    // Show expiration info
    const gmExp = formatExpirationInfo(t.gameManagerCodeExpiresAt);
    const smExp = formatExpirationInfo(t.statManagerCodeExpiresAt);
    
    let info = `
        <div style="margin: 15px 0; padding: 12px; background: #1a1a1a; border-radius: 5px; border-left: 3px solid #0ea5e9;">
            <strong>Game Manager Code (GM)</strong><br>
            Format: GM-XXXXXX<br>
            ${gmExp}<br><br>
            <strong>Stat Manager Code (SM)</strong><br>
            Format: SM-XXXXXX<br>
            ${smExp}
        </div>
        <div style="margin: 15px 0; padding: 12px; background: #1a1a1a; border-radius: 5px; border-left: 3px solid #f59e0b;">
            <strong>⏰ Expiration Rules:</strong><br>
            • Codes are generated by Team Manager<br>
            • Activation: Game day at 12:01 AM<br>
            • Expiration: 2 hours after game final time<br>
            • One-time use per game
        </div>
    `;
    
    const infoDiv = document.getElementById("access-code-info");
    if (infoDiv) {
      infoDiv.innerHTML = info;
    }

    modal.classList.remove("hidden");
}

async function saveCodes() {
    const payload = {
        gameManagerCode: scoreInput.value,
        statManagerCode: statInput.value
    };

    const res = await authFetch(`/teams/${editingTeamId}/codes`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
    });

    if (!res.ok) {
      console.error("Failed to save codes:", res.status);
      if (res.status === 403) {
        showMessage("You do not have permission to update access codes", "error");
      } else {
        showMessage("Failed to save access codes", "error");
      }
      return;
    }

    modal.classList.add("hidden");
    loadCodes();
}

// Event Listeners
document.getElementById("cancel-modal").addEventListener("click", () => modal.classList.add("hidden"));
document.getElementById("save-code-btn").addEventListener("click", saveCodes);

// Logout
document.getElementById("logout-btn").addEventListener("click", () => {
    localStorage.removeItem("nf_token");
    localStorage.removeItem("nf_role");
    window.location.href = "./login.html";
});

// Show message helper (reuse from rosters.js or define locally)
function showMessage(message, type = "info", duration = 3500) {
  const container = document.createElement("div");
  container.id = `msg-${Date.now()}`;
  container.style.cssText = `
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 11000;
  `;

  let borderColor = "#333";
  let icon = "ℹ️";
  if (type === "success") {
    borderColor = "#10b981";
    icon = "✓";
  } else if (type === "error") {
    borderColor = "#ef4444";
    icon = "✕";
  }

  container.innerHTML = `
    <div style="
      background-color: #0f0f0f;
      color: #e8e8e8;
      border: 1px solid ${borderColor};
      border-radius: 10px;
      padding: 20px;
      max-width: 400px;
      box-shadow: 0 0 30px rgba(0, 0, 0, 0.7);
      text-align: center;
    ">
      <div style="font-size: 16px; font-weight: 600;">${icon} ${message}</div>
    </div>
  `;
  
  document.body.appendChild(container);
  setTimeout(() => container.remove(), duration);
}

// Init
await loadCodes();
