name: Deploy Admin Portal Dev

on:
  push:
    branches:
      - main
    paths:
      - web/admin-portal/**
      - .github/workflows/deploy-admin-portal-dev.yml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Deploy Admin Portal to Storage
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Azure CLI storage preview extension
        run: az extension add --name storage-preview --upgrade

      - name: Sync Admin Portal to Storage static website
        run: |
          az storage blob sync \
            --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_ADMIN_DEV }}" \
            --container '$web' \
            --source 'web/admin-portal' \
            --delete-destination true \
            --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY_ADMIN_DEV }}"
